### ISSUE TITLE
파일 수정 시간 비교 관련 정보 조사

### ISSUE THREAD

**Issue by Sung-Wonjin** [Sung-Wonjin/Project2#10]

**Comment by minwooch** [comment]
파일의 정보를 stat()함수로 받아왔을 때, 구조체 stat의 st_mtime에 접근하면 마지막 수정 날짜를 알 수 있습니다.
st_mtime은 구조체 tm입니다. tm.tm_hour에 시간이 tm.tm_min에 분이 들어있으므로 두 파일의 이 시간과 분을 비교하면 됩니다.
